
version: 2

models:

#   - name: my_first_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null

#   - name: my_second_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null


  - name: converted_day_week_month
    description: "question 1"
  - name: top_sources
    description: "question 2"
  - name: conversion_causes
    description: "question 3"
  - name: opportunity_data
    description: "base table joining all details of leads and accounts for each opportunity created"
  - name: opp_won_times


   
